// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/EncryptAny/AditumAllAPI/design
// --out=$(GOPATH)/src/github.com/EncryptAny/AditumAllAPI
// --version=v1.1.0-dirty
//
// API "aditum-all": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app

import (
	"fmt"
	"strings"
)

// VenueHref returns the resource href.
func VenueHref(venueID interface{}) string {
	paramvenueID := strings.TrimLeftFunc(fmt.Sprintf("%v", venueID), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/venue/%v", paramvenueID)
}
